name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: "Choose test"
        required: true
        default: test_1
        type: choice
        options:
          - test_1
          - test_2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Microsoft Edge
        run: sudo apt-get install -y microsoft-edge-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test_1
        if: ${{ github.event.inputs.deployment_target == 'test_1' }}
        run: pytest tests/test_simple_button.py::test_simple_button

      - name: Run test_2
        if: ${{ github.event.inputs.deployment_target == 'test_2' }}
        run: pytest tests/test_simple_button.py::test_like_button
